/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Core.Control;
import java.awt.Dimension;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author jly09
 */
public class ReceptionistMenuForm extends javax.swing.JFrame {
    Control control = null;
    CreateJobForm createJobForm;
    JobForm jobForm;
    DisplayInvoiceForm displayInvoiceForm;
    AddPartForm addPartForm;
    DisplayAllParts displayAllParts;
    OrderPartForm orderPartForm;
    AddSupplierForm addSupplierForm;
    ReportForm reportForm;

    /**
     * Creates new form MenuForm
     */
    public ReceptionistMenuForm() {
        initComponents();
        
        this.setSize(new Dimension(1100, 810));
        this.setPreferredSize(new Dimension(1100, 810));
        
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public ReceptionistMenuForm(Control c) {
        initComponents();

        control = c;
        control.getWindowList().add(this);
        
        this.setSize(new Dimension(1100, 810));
        this.setPreferredSize(new Dimension(1100, 810));
        
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    @Override
    public void dispose() {
        super.dispose();
        control.terminateThread();
    }

    public void setControl(Control c) {
        control = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        displayPrintInvoice_btn = new javax.swing.JButton();
        generateStockReport_btn = new javax.swing.JButton();
        orderParts_btn = new javax.swing.JButton();
        displayUpdateJobs_btn = new javax.swing.JButton();
        createJob_btn = new javax.swing.JButton();
        displayUpdateParts_btn = new javax.swing.JButton();
        stock_lbl = new javax.swing.JLabel();
        job_lbl = new javax.swing.JLabel();
        logout_btn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        addParts_btn = new javax.swing.JButton();
        addSupplier_btn = new javax.swing.JButton();
        report_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        displayPrintInvoice_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        displayPrintInvoice_btn.setText("Display and Print Invoice");
        displayPrintInvoice_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayPrintInvoice_btnActionPerformed(evt);
            }
        });

        generateStockReport_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        generateStockReport_btn.setText("Generate Stock Report");
        generateStockReport_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateStockReport_btnActionPerformed(evt);
            }
        });

        orderParts_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        orderParts_btn.setText("Order Parts");
        orderParts_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderParts_btnActionPerformed(evt);
            }
        });

        displayUpdateJobs_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        displayUpdateJobs_btn.setText("Display and Update Jobs");
        displayUpdateJobs_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayUpdateJobs_btnActionPerformed(evt);
            }
        });

        createJob_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createJob_btn.setText("Create Job");
        createJob_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJob_btnActionPerformed(evt);
            }
        });

        displayUpdateParts_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        displayUpdateParts_btn.setText("Display and Update Parts");
        displayUpdateParts_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayUpdateParts_btnActionPerformed(evt);
            }
        });

        stock_lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        stock_lbl.setText("Stock");

        job_lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        job_lbl.setText("Job");

        logout_btn.setText("Logout");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });

        addParts_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addParts_btn.setText("Add Parts");
        addParts_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addParts_btnActionPerformed(evt);
            }
        });

        addSupplier_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addSupplier_btn.setText("Add Supplier");
        addSupplier_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSupplier_btnActionPerformed(evt);
            }
        });

        report_lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        report_lbl.setText("Report");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout_btn)
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(job_lbl)
                        .addGap(254, 254, 254)
                        .addComponent(stock_lbl)
                        .addGap(227, 227, 227)
                        .addComponent(report_lbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayUpdateJobs_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displayPrintInvoice_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createJob_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayUpdateParts_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderParts_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addParts_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(generateStockReport_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addSupplier_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 974, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(logout_btn)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(job_lbl)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stock_lbl)
                        .addComponent(report_lbl)))
                .addGap(19, 19, 19)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createJob_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addParts_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateStockReport_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(displayUpdateJobs_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(displayPrintInvoice_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(displayUpdateParts_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(orderParts_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addSupplier_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1100, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateStockReport_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateStockReport_btnActionPerformed
        reportForm = new ReportForm(control, this);
        reportForm.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_generateStockReport_btnActionPerformed

    private void displayUpdateParts_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayUpdateParts_btnActionPerformed
        displayAllParts = new DisplayAllParts(control, this);
        displayAllParts.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_displayUpdateParts_btnActionPerformed

    private void addParts_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addParts_btnActionPerformed
        addPartForm = new AddPartForm(control, this);
        addPartForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addParts_btnActionPerformed

    private void addSupplier_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSupplier_btnActionPerformed
        addSupplierForm = new AddSupplierForm(control, this);
        addSupplierForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addSupplier_btnActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        control.logout();
        this.dispose();
    }//GEN-LAST:event_logout_btnActionPerformed

    private void createJob_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJob_btnActionPerformed
        createJobForm = new CreateJobForm(control, this);
        createJobForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createJob_btnActionPerformed

    private void displayUpdateJobs_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayUpdateJobs_btnActionPerformed
        jobForm = new JobForm(control, this);
        jobForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_displayUpdateJobs_btnActionPerformed

    private void displayPrintInvoice_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayPrintInvoice_btnActionPerformed
        displayInvoiceForm = new DisplayInvoiceForm(control, this);
        displayInvoiceForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_displayPrintInvoice_btnActionPerformed

    private void orderParts_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderParts_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderParts_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptionistMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptionistMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptionistMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptionistMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceptionistMenuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addParts_btn;
    private javax.swing.JButton addSupplier_btn;
    private javax.swing.JButton createJob_btn;
    private javax.swing.JButton displayPrintInvoice_btn;
    private javax.swing.JButton displayUpdateJobs_btn;
    private javax.swing.JButton displayUpdateParts_btn;
    private javax.swing.JButton generateStockReport_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel job_lbl;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton orderParts_btn;
    private javax.swing.JLabel report_lbl;
    private javax.swing.JLabel stock_lbl;
    // End of variables declaration//GEN-END:variables
}
